blog/urls.py
from django.conf.urls import url
from . import views
from .views import FacetedSearchView, autocomplete

app_name='blog'
urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/user/(?P<pk>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^find/', FacetedSearchView.as_view(), name='haystack_search'),
    url(r'^grass-to-grace/$', views.GrassToGraceView.as_view(), name='grass_to_grace'),
    url(r'^post/(?P<slug>[-\w]+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    url(r'^create_subscriber/$', views.SubscribeView.as_view(), name='subscribe'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact_us'),
    url(r'^privacy/$', views.PrivacyView.as_view(), name='privacy_policy'),
    url(r'^terms_of_use/$', views.TermsView.as_view(), name='terms'),#test
   url(r'^activate/$', views.activate, name='activate'),
    url(r'^addview/$', views.increaseView, name='addview'),
    url(r'^newsfeed/$', views.newsfeed.as_view(), name='newsfeed'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from django.contrib import auth
from blog.views import autocomplete
app_name='blog'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^imagefit/', include('imagefit.urls')),
    url(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'', include('blog.urls')),
    url(r'^search/autocomplete/$', autocomplete),
    url(r'account/', include('account.urls')),
    url(r'^dashboard/', include('advert.urls')),
    url(r'^password_reset/$', auth.views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth.views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth.views.password_reset_complete, name='password_reset_complete'),
    #url(r'^admin/password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
   # url(r'^newsletter/', include('newsletter_signup.urls')),
]

blog/forms.py
from django import forms
from haystack.forms import FacetedSearchForm
from .models import Post, Comment,  ContactMessage, SubscribeEmail


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text','post_pic')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control borderprob' }),
            'text': forms.Textarea(attrs={'class': ' form-control'}),

        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass form-control'}),
            'text': forms.Textarea(attrs={'id': 'comment-text','class': 'form-control'}),

        }


class FacetedPostSearchForm(FacetedSearchForm):

    def __init__(self, *args, **kwargs):
        data = dict(kwargs.get("data", []))
        self.text = data.get('text', [])
        self.title = data.get('title', [])
        super(FacetedPostSearchForm, self).__init__(*args, **kwargs)

    def search(self):
        sqs = super(FacetedPostSearchForm, self).search()
        if self.text:
            query = None
            for item in self.text:
                if query:
                    query += u' OR '
                else:
                    query = u''
                query += u'"%s"' % sqs.query.clean(item)
            sqs = sqs.narrow(u'category_exact:%s' % query)
        if self.title:
            query = None
            for item in self.title:
                if query:
                    query += u' OR '
                else:
                    query = u''
                query += u'"%s"' % sqs.query.clean(item)
            sqs = sqs.narrow(u'brand_exact:%s' % query)
        return sqs



class ContactForm(forms.ModelForm):

    class Meta:
        model=ContactMessage
        fields=('name','email','phone','message')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'textinputclass form-control', 'placeholder':'Name', 'required':True}),
            'email': forms.EmailInput(attrs={'class': 'textinputclass form-control', 'placeholder':'Email', 'required':True}),
            'phone': forms.TextInput(attrs={'class': 'textinputclass form-control', 'placeholder':'Phone', 'required':True}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Message', 'required':True}),

        }

class SubscribeForm(forms.ModelForm):
    class Meta:
        model=SubscribeEmail
        fields=('email',)
    


#ffjfjfj

blog/views.py
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from blog.models import Post, Comment, Category, SubscribeEmail
from account.models import Profile
from django.contrib import messages
from django.utils import timezone
<<<<<<< HEAD
import datetime
=======
from django.views import View
>>>>>>> 0d919bdf5bd777a66025a33d842a42570bc969ff
from advert.models import Advert
from blog.forms import PostForm, CommentForm, FacetedPostSearchForm, SubscribeForm, ContactForm
from random import choice
from django.utils.encoding import force_bytes, force_text
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView,
                                  FormView)
from .tokens import account_activation_token
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from haystack.generic_views import FacetedSearchView as BaseFacetedSearchView
from haystack.query import SearchQuerySet
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Q
from django.utils.crypto import get_random_string
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import pdb
import json




class AboutView(TemplateView):
    template_name = 'about.html'


class ProfileView(DetailView):
    template_name = 'profile_detail.html'
    model = Profile
    slug_field = "user"

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['profile_list'] = Profile.objects.all()
        context['post_list'] = Post.objects.all()
        context['post_count'] = Post.objects.count()
        adverts=Advert.objects.filter(plan__name__icontains='Prem')
        advert_index=[ advert.pk for advert in adverts]
        fetch_index=choice(advert_index)
        context['ad']=Advert.objects.get(pk=fetch_index)
        
        
        return context


class GrassToGraceView(ListView):
    template_name ='grass-to-grace.html'

    def get_context_data(self, **kwargs):
        context = super(GrassToGraceView, self).get_context_data(**kwargs)
        story_cat = Category.objects.get(name='my story')
        context['story_posts'] = Post.objects.filter(category = story_cat)
        adverts=Advert.objects.filter(plan__name__icontains='Prem')
        advert_index=[ advert.pk for advert in adverts]
        fetch_index=choice(advert_index)
        context['ad']=Advert.objects.get(pk=fetch_index)
        return context

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

# Category View
def show_category(request,hierarchy= None):
    category_slug = hierarchy.split('/')
    category_queryset = list(Category.objects.all())
    all_slugs = [ x.slug for x in category_queryset ]
    adverts=Advert.objects.filter(plan__name__icontains='Prem')
    advert_index=[ advert.pk for advert in adverts]
    fetch_index=choice(advert_index)
    parent = None
    for slug in category_slug:
        if slug in all_slugs:
            parent = get_object_or_404(Category,slug=slug,parent=parent)
        else:
            instance = get_object_or_404(Post, slug=slug)
            breadcrumbs_link = instance.get_cat_list()
            category_name = [' '.join(i.split('/')[-1].split('-')) for i in breadcrumbs_link]
            breadcrumbs = zip(breadcrumbs_link, category_name)
            return render(request, "post_detail.html", {'instance':instance,'breadcrumbs':breadcrumbs})

    return render(request,"category.html",{'post_set':parent.post_set.all().order_by('-published_date'),'sub_categories':parent.children.all(), 'ad':Advert.objects.get(pk=fetch_index)})


class PostListView(ListView):
    model = Post
    paginate_by = 5


    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['post_list'] = Post.objects.exclude(Q(category__name__icontains='my st'), featured_post=False).filter(status__icontains='publis').order_by('-created_date')
        context['profile_list'] = Profile.objects.all()
        context['featured_posts'] = Post.objects.filter(featured_post=True).exclude(category__name__icontains='my sto').filter(status__icontains='publis').order_by('-published_date')[:5]
        context['trending_posts'] = Post.objects.filter(trending_post=True).exclude(category__name__icontains='my sto').filter(status__icontains='publis')
        context['latest_posts'] =  Post.objects.filter(published_date__lte=timezone.now()).filter(status__icontains='publis').exclude(featured_post=True).order_by('-published_date')[7:14]
        context['fashion_posts'] = Post.objects.filter(category__name__icontains = 'fashion').filter(status__icontains='publis').order_by('-published_date')
        context['business_posts'] = Post.objects.filter(category__name__icontains = 'business').filter(status__icontains='publis').order_by('-published_date')
<<<<<<< HEAD
        context['entertainment_posts'] = Post.objects.filter(category__name__icontains='entertainment').filter(status__icontains='publis').order_by('-published_date')[3:8]
        context['tech_posts'] = Post.objects.filter(category__name__icontains='technology').filter(status__icontains='publis').order_by('-published_date')[3:8]
        context['pol_posts'] = Post.objects.filter(category__name__icontains='politics').filter(status__icontains='publis').order_by('-published_date')[3:8]

        context['post_story']=Post.objects.get(Q(category__name__icontains='my sto'), featured_post=True )#rtrtrtrt
        context['lnp']=Post.objects.filter(category__name__icontains='news').filter(status__icontains='publis').order_by('-published_date')[:15]
=======
        context['entertainment_posts'] = Post.objects.filter(category__name__icontains='entertainment').filter(status__icontains='publis').order_by('-published_date')
        context['tech_posts'] = Post.objects.filter(category__name__icontains='techn').filter(status__icontains='publis').order_by('-published_date')
        context['pol_posts'] = Post.objects.filter(category__name__icontains='politics').filter(status__icontains='publis').order_by('-published_date')
        #context['post_story']=Post.objects.get(Q(category__name__icontains='my sto'), featured_post=True )#rtrtrtrt
        context['lnp']=Post.objects.filter(category__name__icontains='news').filter(status__icontains='publis').exclude(featured_post=True).order_by('-published_date')[:15]
>>>>>>> 0d919bdf5bd777a66025a33d842a42570bc969ff
        listed_post = Post.objects.all()
        paginator = Paginator(listed_post, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            list_posts = paginator.page(page)
        except PageNotAnInteger:
            list_posts = paginator.page(1)
        except EmptyPage:  #d
            list_posts = paginator.page(paginator.num_pages)

        context['listed_posts'] = list_posts
        return context

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        post=self.get_object()
        name=post.category.name
        context['Comments'] = Comment.objects.all()
        context['post_list'] = Post.objects.all()
        story_cat = Category.objects.get(name='my story')
        context['story_posts'] = Post.objects.filter(category = story_cat)
        context['featured_posts'] = Post.objects.filter(featured_post=True).order_by('-published_date')
        context['similar_posts']=Post.objects.filter(category__name__icontains=name).exclude(id=post.id)[:6]
        context['trending_posts'] = Post.objects.filter(trending_post=True).exclude(id=post.id)
        context['recent_posts'] = Post.objects.filter(published_date__lte=timezone.now()).exclude(id=post.id).order_by('-published_date')
        context['form'] = CommentForm
        context['approved_comments'] = Comment.objects.filter(approved_comment=True)
        adverts=Advert.objects.filter(plan__name__icontains='Prem')
        advert_index=[ advert.pk for advert in adverts]
        fetch_index=choice(advert_index)
        context['ad']=Advert.objects.get(pk=fetch_index)
        context['lnp']=Post.objects.filter(category__name__icontains='news').filter(status__icontains='publis').exclude(featured_post=True).order_by('-published_date')[:3]
        
        return context



class newsfeed(View):
    def get(self, request, *args, **kwargs ):
        news=dict()
        news['status']=True
        template='blog/includes/lnp.html'
        a= self.request.GET.get('no')
        a=int(a)

        if a and a > 1:
            newsfeed=Post.objects.filter(category__name__icontains='news').filter(status__icontains='publis').exclude(featured_post=True).order_by('-published_date')[:a]
            newsfeed=render_to_string(template, {'lnp':newsfeed} )
            news['news']=newsfeed
            return JsonResponse(news)
        else:
            news['status']=False
            return JsonResponse(news)     





class CommentFormView(FormView):
    form_class = CommentForm
    success_url = "/"

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.

blog/templates/blog/includes/googleanalytics.html
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-106246012-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'UA-106246012-2');
</script>

blog/templates/blog/includes/lnp.html
{% load imagefit %}
<!--div class="zone-title text-center">
                    <h1 class="zone-title-text">News Feed</h1>
              </div>
            
             <div class='checking'>
              <a href="{{post.get_absolute_url}}">
              <div class="row margin-tops">
                <div class="col-xl-6 col-xs-5 sidebarrowCol">
                  <img class="img-responsive" style="width: 120px;" src="{{post.post_pic.url|resize:'200x200,C'}}"/>
                </div>
                <div class="col-xl-6 col-xs-7 no-pad zone-content ">
                  <h4>{{post.title}}</h4>
                  
                </div>
                <br>
              </div>
              </a>
              <hr>
            </div-->
            <div class="grid-mod-card-list">
              <div class="zone-title text-center">
                    <h1 class="zone-title-text">News Feed</h1>
              </div>
                                     <ul>
                {% for post in lnp %}
                  
                                  
                                      <li class="story storydetail">
                                        <a href="{{post.get_absolute_url}}">
                                          <span class="image"  style="background-image: url({{post.post_pic.url}});"></span>
                                          <h2>{{post.title|truncatechars:70}}</h2>
                                        </a>
                                      </li>
                                     

                {% endfor %}  
                </ul>
                                  </div>
             

blog/templates/blog/includes/messages.html
{% for message in messages %}
<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
{% endfor %}

blog/templates/blog/includes/newsfeed.html
{% load imagefit %}
{% for post in lnp|slice:"1:6"  %}
							<a href="{{post.get_absolute_url}}">
							<div class="row sidebarrow">
								<div class="col-xl-6 col-xs-5 sidebarrowCol">
									<img class="img-responsive" height="70px" src="{{post.post_pic.url|resize:'200x200,C'}}"/>
								</div>
								<div class="col-xl-6 col-xs-7 no-pad zone-content ">
									<h4>{{post.title}}</h4>
									<!--p>{{post.text|truncatechars:40|safe}} </p-->
								</div>
								<br>
							</div>
							</a>
							<hr>
							{% endfor %}

blog/templates/blog/includes/recommended_partial.html
{% load imagefit %}
<div class="row">
                  <h3 style="">You Might Also Like</h3>
                  </div>

                  <div class="row">
                  {% for post in featured_posts|slice:"0:6" %}
                  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 pad-right"><a href="{{post.get_absolute_url}}">
                    <div class= "wrappertwo storywrapper" style="">
                       <a href="{{post.get_absolute_url}}">
                  <div class="imagewapper">
                    <div class="image image-align" style="background-image: url({{post.post_pic.url}})"></div>
                  </div>
                  <div class="content">
                    <h2>{{post.title}}</h2>
                  </div>
                </div> 
              </a>
              </div>
                  {% endfor %}
                </div>
                
                

blog/templates/blog/includes/subscribe_email.html
{% autoescape off %}
Hi ,
Please click on the link to confirm your Subscription on AvetiZBlog,

https://avetizblog.com{% url 'blog:activate' %}?token={{token}}&email={{email}}
{% endautoescape %}