blog/urls.py
from django.conf.urls import url
from . import views
from .views import FacetedSearchView, autocomplete

app_name='blog'
urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/user/(?P<pk>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^find/', FacetedSearchView.as_view(), name='haystack_search'),
    url(r'^grass-to-grace/$', views.GrassToGraceView.as_view(), name='grass_to_grace'),
    url(r'^post/(?P<slug>[-\w]+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    url(r'^create_subscriber/$', views.SubscribeView.as_view(), name='subscribe'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact_us'),
    url(r'^privacy/$', views.PrivacyView.as_view(), name='privacy_policy'),
    url(r'^terms_of_use/$', views.TermsView.as_view(), name='terms'),#test
   url(r'^activate/$', views.activate, name='activate'),
    url(r'^addview/$', views.increaseView, name='addview'),
    url(r'^newsfeed/$', views.newsfeed.as_view(), name='newsfeed'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from django.contrib import auth
from blog.views import autocomplete
app_name='blog'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^imagefit/', include('imagefit.urls')),
    url(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'', include('blog.urls')),
    url(r'^search/autocomplete/$', autocomplete),
    url(r'account/', include('account.urls')),
    url(r'^dashboard/', include('advert.urls')),
    url(r'^password_reset/$', auth.views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth.views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth.views.password_reset_complete, name='password_reset_complete'),
    #url(r'^admin/password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
   # url(r'^newsletter/', include('newsletter_signup.urls')),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
#from django.utils.encoding import smart_unicode




class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=400)
    text = models.TextField(blank=True)
    post_pic = models.ImageField(upload_to='media', blank=True, null=True)
    
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    featured_post = models.BooleanField(default=False)
    trending_post = models.BooleanField(default=False)
    status = models.CharField(max_length=100, default="Draft", choices=(('Draft','Draft'),('Published','Published'),('Submitted','Submitted')))
    category = models.ForeignKey('Category', null=True, blank=True)
    pageview=models.IntegerField(default=0)
    slug = models.SlugField(null=True, blank=True, max_length=200)
    

    def publish(self):
        if self.post_pic and self.text:
            self.published_date = timezone.now()
            self.status = 'Published'
            self.save()
            return True
        else:
            return False

    def submit(self):
        if self.post_pic and self.text:
            self.status='Submitted'
            self.save()
            return True
        else:
            return False

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)
       


    def approve_comments(self):
        return self.comments.filter(approved_comment=True)


    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})


    def get_cat_list(self):
        k = self.category
        breadcrumb = ["dummy"]
        while k is not None:
            breadcrumb.append(k.slug)
            k = k.parent

        for i in range(len(breadcrumb)-1):
            breadcrumb[i] = '/'.join(breadcrumb[-1:i-1:-1])
        return breadcrumb[-1:0:-1]

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    parent = models.ForeignKey('self',blank=True, null=True, related_name='children')

    class Meta:
        unique_together = ('slug', 'parent',)
        verbose_name_plural = "categories"

    def __str__(self):
        full_path = [self.name]
        k = self.parent

        while k is not None:
            full_path.append(k.name)
            k = k.parent

        return ' -> '.join(full_path[::-1])



class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self): 
        return self.text


class SubscribeEmail(models.Model):
    email=models.EmailField()
    active=models.BooleanField(default=False)
    token=models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return self.email

class ContactMessage(models.Model):
    name=models.CharField(max_length=200)
    email=models.EmailField()
    phone=models.CharField(max_length=200)
    message=models.TextField()

blog/views.py
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from blog.models import Post, Comment, Category, SubscribeEmail
from account.models import Profile
from django.contrib import messages
from django.utils import timezone
<<<<<<< HEAD
import datetime
=======
from django.views import View
>>>>>>> 0d919bdf5bd777a66025a33d842a42570bc969ff
from advert.models import Advert
from blog.forms import PostForm, CommentForm, FacetedPostSearchForm, SubscribeForm, ContactForm
from random import choice
from django.utils.encoding import force_bytes, force_text
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView,
                                  FormView)
from .tokens import account_activation_token
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from haystack.generic_views import FacetedSearchView as BaseFacetedSearchView
from haystack.query import SearchQuerySet
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Q
from django.utils.crypto import get_random_string
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import pdb
import json




class AboutView(TemplateView):
    template_name = 'about.html'


class ProfileView(DetailView):
    template_name = 'profile_detail.html'
    model = Profile
    slug_field = "user"

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['profile_list'] = Profile.objects.all()
        context['post_list'] = Post.objects.all()
        context['post_count'] = Post.objects.count()
        adverts=Advert.objects.filter(plan__name__icontains='Prem')
        advert_index=[ advert.pk for advert in adverts]
        fetch_index=choice(advert_index)
        context['ad']=Advert.objects.get(pk=fetch_index)
        
        
        return context


class GrassToGraceView(ListView):
    template_name ='grass-to-grace.html'

    def get_context_data(self, **kwargs):
        context = super(GrassToGraceView, self).get_context_data(**kwargs)
        story_cat = Category.objects.get(name='my story')
        context['story_posts'] = Post.objects.filter(category = story_cat)
        adverts=Advert.objects.filter(plan__name__icontains='Prem')
        advert_index=[ advert.pk for advert in adverts]
        fetch_index=choice(advert_index)
        context['ad']=Advert.objects.get(pk=fetch_index)
        return context

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

# Category View
def show_category(request,hierarchy= None):
    category_slug = hierarchy.split('/')
    category_queryset = list(Category.objects.all())
    all_slugs = [ x.slug for x in category_queryset ]
    adverts=Advert.objects.filter(plan__name__icontains='Prem')
    advert_index=[ advert.pk for advert in adverts]
    fetch_index=choice(advert_index)
    parent = None
    for slug in category_slug:
        if slug in all_slugs:
            parent = get_object_or_404(Category,slug=slug,parent=parent)
        else:
            instance = get_object_or_404(Post, slug=slug)
            breadcrumbs_link = instance.get_cat_list()
            category_name = [' '.join(i.split('/')[-1].split('-')) for i in breadcrumbs_link]
            breadcrumbs = zip(breadcrumbs_link, category_name)
            return render(request, "post_detail.html", {'instance':instance,'breadcrumbs':breadcrumbs})

    return render(request,"category.html",{'post_set':parent.post_set.all().order_by('-published_date'),'sub_categories':parent.children.all(), 'ad':Advert.objects.get(pk=fetch_index)})


class PostListView(ListView):
    model = Post
    paginate_by = 5


    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['post_list'] = Post.objects.exclude(Q(category__name__icontains='my st'), featured_post=False).filter(status__icontains='publis').order_by('-created_date')
        context['profile_list'] = Profile.objects.all()
        context['featured_posts'] = Post.objects.filter(featured_post=True).exclude(category__name__icontains='my sto').filter(status__icontains='publis').order_by('-published_date')[:5]
        context['trending_posts'] = Post.objects.filter(trending_post=True).exclude(category__name__icontains='my sto').filter(status__icontains='publis')
        context['latest_posts'] =  Post.objects.filter(published_date__lte=timezone.now()).filter(status__icontains='publis').exclude(featured_post=True).order_by('-published_date')[7:14]
        context['fashion_posts'] = Post.objects.filter(category__name__icontains = 'fashion').filter(status__icontains='publis').order_by('-published_date')
        context['business_posts'] = Post.objects.filter(category__name__icontains = 'business').filter(status__icontains='publis').order_by('-published_date')
<<<<<<< HEAD
        context['entertainment_posts'] = Post.objects.filter(category__name__icontains='entertainment').filter(status__icontains='publis').order_by('-published_date')[3:8]
        context['tech_posts'] = Post.objects.filter(category__name__icontains='technology').filter(status__icontains='publis').order_by('-published_date')[3:8]
        context['pol_posts'] = Post.objects.filter(category__name__icontains='politics').filter(status__icontains='publis').order_by('-published_date')[3:8]

        context['post_story']=Post.objects.get(Q(category__name__icontains='my sto'), featured_post=True )#rtrtrtrt
        context['lnp']=Post.objects.filter(category__name__icontains='news').filter(status__icontains='publis').order_by('-published_date')[:15]
=======
        context['entertainment_posts'] = Post.objects.filter(category__name__icontains='entertainment').filter(status__icontains='publis').order_by('-published_date')
        context['tech_posts'] = Post.objects.filter(category__name__icontains='techn').filter(status__icontains='publis').order_by('-published_date')
        context['pol_posts'] = Post.objects.filter(category__name__icontains='politics').filter(status__icontains='publis').order_by('-published_date')
        #context['post_story']=Post.objects.get(Q(category__name__icontains='my sto'), featured_post=True )#rtrtrtrt
        context['lnp']=Post.objects.filter(category__name__icontains='news').filter(status__icontains='publis').exclude(featured_post=True).order_by('-published_date')[:15]
>>>>>>> 0d919bdf5bd777a66025a33d842a42570bc969ff
        listed_post = Post.objects.all()
        paginator = Paginator(listed_post, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            list_posts = paginator.page(page)
        except PageNotAnInteger:
            list_posts = paginator.page(1)
        except EmptyPage:  #d
            list_posts = paginator.page(paginator.num_pages)

        context['listed_posts'] = list_posts
        return context

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        post=self.get_object()
        name=post.category.name
        context['Comments'] = Comment.objects.all()
        context['post_list'] = Post.objects.all()
        story_cat = Category.objects.get(name='my story')
        context['story_posts'] = Post.objects.filter(category = story_cat)
        context['featured_posts'] = Post.objects.filter(featured_post=True).order_by('-published_date')
        context['similar_posts']=Post.objects.filter(category__name__icontains=name).exclude(id=post.id)[:6]
        context['trending_posts'] = Post.objects.filter(trending_post=True).exclude(id=post.id)
        context['recent_posts'] = Post.objects.filter(published_date__lte=timezone.now()).exclude(id=post.id).order_by('-published_date')
        context['form'] = CommentForm
        context['approved_comments'] = Comment.objects.filter(approved_comment=True)
        adverts=Advert.objects.filter(plan__name__icontains='Prem')
        advert_index=[ advert.pk for advert in adverts]
        fetch_index=choice(advert_index)
        context['ad']=Advert.objects.get(pk=fetch_index)
        context['lnp']=Post.objects.filter(category__name__icontains='news').filter(status__icontains='publis').exclude(featured_post=True).order_by('-published_date')[:3]
        
        return context



class newsfeed(View):
    def get(self, request, *args, **kwargs ):
        news=dict()
        news['status']=True
        template='blog/includes/lnp.html'
        a= self.request.GET.get('no')
        a=int(a)

        if a and a > 1:
            newsfeed=Post.objects.filter(category__name__icontains='news').filter(status__icontains='publis').exclude(featured_post=True).order_by('-published_date')[:a]
            newsfeed=render_to_string(template, {'lnp':newsfeed} )
            news['news']=newsfeed
            return JsonResponse(news)
        else:
            news['status']=False
            return JsonResponse(news)     





class CommentFormView(FormView):
    form_class = CommentForm
    success_url = "/"

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}

<h1>About me</h1>
<p>Thanks for visiting my blog! Check all this cool stuff about me!</p>

{% endblock %}

blog/templates/blog/advertise.html
{% extends 'blog/base.html' %}
{% load static %}

        {% block links %}
        <link href="{% static 'css/flexslider.css' %}" rel="stylesheet">
        <link href="{% static 'css/animate.css' %}" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <!--custom css for only medial template-->
        <link href="{% static 'css/contact.css' %}" type="text/css" rel="stylesheet">
        {% endblock %}

       
    
   
{% block content %}    
        <div id="map-canvas" style="width: 100%; height: 400px;"></div>
        <div class="divide70"></div>
         {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
          </div>
        {% endfor %}
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-8">
                    <div class="text-center"><h2>Advertise With Us</h2></div>
                    <div class="contact-form-col">
                        <p>Please stay in touch with AvetiZ by completing the details below. </p>
                        <form name="sentMessage" id="contactForm" method="post" novalidate>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row control-group">
                                        <div class="form-group col-xs-12 controls">                                        
                                            <!--input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name."-->
                                            {{form.name}}
                                            <p style="color:red" class="help-block">{{form.name.errors}}</p>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="row control-group">
                                        <div class="form-group col-xs-12 controls">                                          
                                            <!--input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address."-->
                                            {{form.email}}
                                            <p style="color:red" class="help-block">{{form.email.errors}}</p>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                            <div class="row control-group">
                                <div class="form-group col-xs-12  controls">                                  
                                    <!--input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number."-->
                                    {{form.phone}}
                                    <p style="color:red" class="help-block">{{form.phone.errors}}</p>
                                </div>
                            </div>
                            <div class="row control-group">
                                <div class="form-group col-xs-12 controls">                                  
                                    <!--textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea-->
                                    {{form.message}}
                                    <p style="color:red" class="help-block">{{form.message.errors}}</p>
                                </div>
                            </div>

                            <div id="success"></div>
                            <div class="row">
                                <div class="form-group col-xs-12">
                                    <button type="submit" class="btn btn-theme-bg btn-lg">Send Message</button>
                                </div>
                            </div>
                        </form>
                        
                    </div>
                    
                </div><!--form col end-->
                <div class="col-md-4 col-sm-4">
                    <div class="" style="margin-bottom: 30px;" >
                        <img height="100px" src="http://test.sagecapitals.com/img/avetiz.jpg"/>
                    </div>
                    <div>
                        <p style="font-size: 20px; line-height: 1.7em; color: #666;"><strong>6th Floor, NICON Plaza,<br>
                        Plot 242 Muhammadu Buhari Way,<br>
                        Central Business District, Abuja,<br>
                        Nigeria.<br><br>
                        <i class="fa fa-phone" style="margin-right: 7px;"></i> 09-2912518, 0908-62-AVETIZ<br>
                        <i class="fa fa-envelope-o" style="margin-right: 7px;"></i> contact@avetizblog.com</strong></p>
                    </div>
                    <div class="sidebar-img-detail margin-tops">
                        <img class="img-responsive"  src="https://tpc.googlesyndication.com/simgad/3498238943114035450"/>
                    </div>
                    <hr>
                    
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <div class="recommended_partial similarStories">
                             {% include 'blog/includes/recommended_partial.html' %}
                         </div>
                    </div>
                    <div class="col-md-4">


                        <div class="sidebar-img-detail margin-tops">
                          <img class="img-responsive" style="width:300px; height:490px"  src="https://tpc.googlesyndication.com/simgad/12095207540805284894" >
                        </div>
                    </div>    
                </div>
            </div>
        </div>

        <div class="divide40"></div>
        
        
        <!--gmap js-->
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDgAaQZdwfk6IBH9cSVM8c-5VJO7K52qQE&sensor=true"></script>
        <script type="text/javascript">
            var myLatlng;
            var map;
            var marker;

            function initialize() {
                myLatlng = new google.maps.LatLng(9.050499, 7.482072);

                var mapOptions = {
                    zoom: 14,
                    center: myLatlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    scrollwheel: false,
                    draggable: false
                };
                map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

                var contentString = '<p style="line-height: 20px; margin-bottom:4px;"><strong style="font-size:20px;">AvetiZ Blog</strong></p>6th Floor NICON Plaza, Plot 242 Muhammadu Buhari Way,Central Business District, Abuja, Nigeria.</p>';

                var infowindow = new google.maps.InfoWindow({
                    content: contentString
                });

                marker = new google.maps.Marker({
                    position: myLatlng,
                    map: map,
                    title: 'Marker'
                });

                google.maps.event.addListener(marker, 'click', function () {
                    infowindow.open(map, marker);
                });
            }

            google.maps.event.addDomListener(window, 'load', initialize);
        </script>
{% endblock %}

{% block topimg %}
<a href="{% url 'blog:grass_to_grace' %}"><img class="img-responsive" src="/media/success.png/"></a>
{% endblock %}

blog/templates/blog/category.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% load imagefit %}


{% block content %}
{% block links %}
<link rel="stylesheet" href="{% static 'css/categories.css' %}">
{% endblock %}
  <!-- Header Section with Advert -->
  <header class="cAdSection">
    <img class="img-responsive" src="https://tpc.googlesyndication.com/simgad/1557534103495319173">
  </header>

  <!-- Category Title Section -->
  <section class="cHeadlineSection">
    <div class="container-fluid">
    <h2></h2>
    </div>
  </section>

  <main class="mainCategory container-fluid">
    <div class="row">


    <!-- Whats New Section -->
      <div class="col-sm-6 col-md-4 col-lg-3 whatsNewCol">
        <h3 class="cTitle"> {{category_name}} What's New</h3>

        <!-- Whats New Articles -->

        {% for i in post_set %}
        <div class="row whatsNewArticle">
          <div class="col-xs-4">
            <img class="img-responsive" src="{{i.post_pic.url|resize:'175x175,C'}}">
          </div>
          <div class="col-xs-8 noleftpad">
            <p class="whatsNewATitle"><a href="{{i.get_absolute_url}}">{{i.title|title}}</a></p>
            <span><i class="fa fa-clock-o " aria-hidden="true"></i> 
            <small>{{i.published_date|timesince}}</small></span>
          </div>
        </div>
        {% endfor %}



        <div class="row adRow">
          <div class="col-xs-12">
          <!-- Categories Show -->
        
          {% if sub_categories %}
              <h3>Sub Categories</h3>
              {% for i in sub_categories %}
                  <a href="{{ i.slug }}"> {{ i.name }} </a>
              {% endfor %}
          {% endif %}
          
          <img class="img-responsive" src="https://tpc.googlesyndication.com/simgad/14899169878083854005">
          
            </div>
        </div>

        {% for post in post_set|slice:"4:13" %}
        <div class="row whatsNewArticle">
          <div class="col-xs-4">
            <img class="img-responsive" src="{{post.post_pic.url|resize:'175x175,C'}}">
          </div>
          <div class="col-xs-8 noleftpad">
            <p class="whatsNewATitle"><a href="{{post.get_absolute_url}}">{{post.title|title}}</a></p>
            <span><i class="fa fa-clock-o " aria-hidden="true"></i> 
            <small>{{post.published_date|timesince}}</small></span>
          </div>
        </div>
        {% endfor %}


        <div class="row adRow">
          <div class="col-xs-12">
          <img class="img-responsive" src="https://tpc.googlesyndication.com/simgad/14899169878083854005">
          
            </div>
        </div>


      </div>


      <!-- Whats Rising Section -->
      <div class="col-sm-6 col-md-4 col-lg-4 whatsRisingCol">

        {% for post in post_set|slice:"4:10" %}
        <div class="card">
                  <div class="card-image">
                      <img class="img-responsive" src="{{post.post_pic.url|resize:'356x205,C'}}">
                  </div>
                  
                  <div class="card-content">
                      <h3 class="whatsRisingATitle"><a href="{{post.get_absolute_url}}">{{post.title|title}}</a></h3>
                  </div>
                  
                  <div class="card-action">
                    <span><i class="fa fa-clock-o " aria-hidden="true"></i> 
                        <small>{{post.published_date|timesince}}</small></span>
                  </div>
              </div>
              {% endfor %}
       

      </div>

      <!-- Whats Hot Section -->

      <div class="hidden-sm col-md-4 col-lg-5 whatsHotCol">
        {% for post in post_set|slice:"6:12"  %}
        <div class="card">
                  <div class="card-image">
                      <img class="img-responsive" src="{{post.post_pic.url|resize:'638x368,C'}}">
                  </div>
                  
                  <div class="card-content">
                      <h3 class="whatsHotATitle"><a href="{{post.get_absolute_url}}">{{post.title|title}}</a>
                      </h3>
                      <div>{{post.text|truncatechars:100|safe|capfirst}}</div>
                  </div>
                  
                  <div class="card-action">
                    <span><i class="fa fa-clock-o " aria-hidden="true"></i> 
                        <small>{{post.published_date|timesince}}</small></span>
                  </div>
              </div>
            {% endfor %}

      </div>
    </div>
  </main>
{% endblock %}
{% block topimg %}
<a href="{{ad.link}}"><img class="img-responsive" src="{{ad.advert_banner.url}}"></a>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Post Comment</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}