account/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views



app_name='account'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^signup/$', views.SignUp.as_view(), name="signup"),
	url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset_form_submit'),
	url(r'^password_change_form/$', views.PasswordChangeView.as_view(), name='password_change_form'),
	#url(r'^password_change/$', views.PasswordChange.as_view(), name="password_change"),ok
    
]

advert/urls.py
from django.conf.urls import url
from . import views

app_name="advert"
urlpatterns = [
     url(r'^$', views.Dashboard.as_view(), name='dashboard'),
     url(r'^post/(?P<pk>\d+)/edit/$', views.postUpdate.as_view(), name='update_post'),
     url(r'^create_post/$', views.createPost.as_view(), name='create_post'),

     url(r'^manage_posts/$', views.postList.as_view(), name='post_list'),
     url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='delete_post'),
      url(r'^report/(?P<pk>\d+)/remove/$', views.ReportDeleteView.as_view(), name='delete_report'),
     url(r'^post/(?P<pk>\d+)/submit/$', views.PostSubmitView.as_view(), name='submit_post'),
     url(r'^post/(?P<pk>\d+)/publish/$', views.PostPublishView.as_view(), name='publish_post'),
     url(r'^post/(?P<pk>\d+)/feature_post/$', views.PostFeatureView.as_view(), name='feature_post'),
     url(r'^manage_wallet/$', views.TransactionListView.as_view(), name='transaction_list'),
     url(r'^create_transaction/$', views.TransactionCreateView.as_view(), name='create_transaction'),
     url(r'^advert_list/$', views.AdvertListView.as_view(), name='advert_list'),
     url(r'^create_advert/$', views.createAdvert.as_view(), name='create_advert'),
     url(r'^advert/(?P<pk>\d+)/remove/$', views.AdvertDeleteView.as_view(), name='delete_advert'),
     url(r'^advert/(?P<pk>\d+)/update/$', views.AdvertUpdateView.as_view(), name='update_advert'),
     url(r'^author/(?P<pk>\d+)/post_list/$', views.AuthorPostView.as_view(), name='author_post_list'),
     url(r'^profile/$', views.ProfileUpdateView.as_view(), name='profile'),
     url(r'^approve_payt/$', views.ApprovePaytView.as_view(), name='approve_payt'),
     url(r'^author_list/$', views.AuthorListView.as_view(), name='author_list'),  
     url(r'^all_post_list/$', views.AllPostView.as_view(), name='all_post_list')  ,
     url(r'^report/$', views.ReportView.as_view(), name='report') , 
     url(r'^create_report/$', views.createReport.as_view(), name='create_report'),
     url(r'^report/(?P<pk>\d+)/detail/$', views.ReportEyeView.as_view(), name='report_posts'),
      url(r'^report/(?P<pk>\d+)/send/$', views.ReportSendView.as_view(), name='send_report'),

]

blog/urls.py
from django.conf.urls import url
from . import views
from .views import FacetedSearchView, autocomplete

app_name='blog'
urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/user/(?P<pk>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^find/', FacetedSearchView.as_view(), name='haystack_search'),
    url(r'^grass-to-grace/$', views.GrassToGraceView.as_view(), name='grass_to_grace'),
    url(r'^post/(?P<slug>[-\w]+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    url(r'^create_subscriber/$', views.SubscribeView.as_view(), name='subscribe'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact_us'),
    url(r'^privacy/$', views.PrivacyView.as_view(), name='privacy_policy'),
    url(r'^terms_of_use/$', views.TermsView.as_view(), name='terms'),#test
   url(r'^activate/$', views.activate, name='activate'),
    url(r'^addview/$', views.increaseView, name='addview'),
    url(r'^newsfeed/$', views.newsfeed.as_view(), name='newsfeed'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from django.contrib import auth
from blog.views import autocomplete
app_name='blog'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^imagefit/', include('imagefit.urls')),
    url(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'', include('blog.urls')),
    url(r'^search/autocomplete/$', autocomplete),
    url(r'account/', include('account.urls')),
    url(r'^dashboard/', include('advert.urls')),
    url(r'^password_reset/$', auth.views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth.views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth.views.password_reset_complete, name='password_reset_complete'),
    #url(r'^admin/password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
   # url(r'^newsletter/', include('newsletter_signup.urls')),
]

advert/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404
from django.views import View
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import advertForm, UserForm, ProfileForm
from .models import Advert, Transaction, Wallet, Report
from blog.models import Post, Comment
from .forms import  PostForm, TransactionForm, reportForm
from account.models import Profile
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.template.loader import render_to_string
import random, string
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.utils.crypto import get_random_string
import pdb

# Create your views here
class Dashboard(LoginRequiredMixin, View):
	login_url='account/login'

	def get(self,request, *args, **kwargs):
		comment_count=Comment.objects.filter(post__author=self.request.user).count()
		draft_count=Post.objects.filter(Q(status__icontains='draft'), author=self.request.user).count()
		amount=Wallet.objects.get(Owner=self.request.user).amount
		published_count=Post.objects.filter(status__icontains='publish').filter(author=self.request.user).count()
		submitted_count=Post.objects.filter(status__icontains='submit').filter(author=self.request.user).count()
		monthdis=monthCount(self.request.user, n=[])
		#pdb.set_trace()
		context={
		'comment_count':comment_count,
		'draft_count':draft_count,
		'amount':amount,	
		'published_count':published_count,
		'submitted_count':submitted_count,
		'monthdis':monthdis,
		}
		return render(self.request, 'advert/dashboard.html', context)
		

class postList(LoginRequiredMixin, ListView):
	model=Post
	template_name='advert/post_list.html'
	login_url='account/login'
	context_object_name='posts'
	paginate_by=10
	def get_queryset(self):
		return Post.objects.filter(author=self.request.user).order_by('-published_date').order_by('-created_date')

class AdvertListView(LoginRequiredMixin,ListView):
	model=Advert
	template_name='advert/advert.html'
	login_url='account/login'
	context_object_name='adverts'

	def get_queryset(self):
		return Advert.objects.filter(publisher=self.request.user)


class AjaxableResponseMixin(object):
	partial_file=None
	partial_success_file=None

	def form_invalid(self, form):
		return HttpResponseRedirect(reverse('advert:post_list'))
        
	def form_valid(self,form):
		post=form.save(commit=False)
		post.author=self.request.user
		post.save()
		dic=dict()
		data=Post.objects.filter(author=self.request.user).order_by('-published_date')
		context={'posts':data}
		dic['form_is_valid']=True
		dic['html_list']=render_to_string(self.partial_success_file,context,request=self.request)
		return HttpResponseRedirect(reverse('advert:post_list'))
		

	def render_to_json_response(self, data):
		return JsonResponse(data)


class createPost(LoginRequiredMixin,AjaxableResponseMixin, CreateView):
	model=Post
	form_class=PostForm
	login_url='account/login'
	partial_success_file='advert/includes/partial_post_list.html'
	partial_file='advert/includes/partial_post_create.html'

	def get(self,request, *args, **kwargs):
		form=PostForm()
		data={'form':form}
		dic = dict()
		dic['html_form'] = render_to_string(self.partial_file, data, request=self.request)
		return self.render_to_json_response(dic)
	

class createAdvert(LoginRequiredMixin,AjaxableResponseMixin, CreateView):
	model=Post
	form_class=advertForm
	login_url='account/login'
	partial_success_file='advert/includes/partial_advert_list.html'
	partial_file='advert/includes/partial_advert_create.html'

	def get(self,request, *args, **kwargs):
		form=advertForm()
		data={'form':form}
		dic = dict()
		dic['html_form'] = render_to_string(self.partial_file, data, request=self.request)
		return self.render_to_json_response(dic)

	def form_valid(self,form):
		advert=form.save(commit=False)
		advert.setUp(self.request.user)
		advert.save()
		dic=dict()
		data=Advert.objects.filter(publisher=self.request.user)
		context={'adverts':data}
		#dic['form_is_valid']=True
		#dic['html_list']=render_to_string(self.partial_success_file,context,request=self.request)
		#return JsonResponse(dic)
		return HttpResponseRedirect(reverse('advert:advert_list'))

class createReport(LoginRequiredMixin,AjaxableResponseMixin, CreateView):
	model=Report
	form_class=reportForm
	login_url='account/login'
	partial_success_file='advert/includes/partial_report_list.html'
	partial_file='advert/includes/partial_report_create.html'

	def get(self,request, *args, **kwargs):
		form=reportForm()
		data={'form':form}
		dic = dict()
		dic['html_form'] = render_to_string(self.partial_file, data, request=self.request)
		return self.render_to_json_response(dic)

	def form_valid(self,form):
		report=form.save(commit=False)
		report.setUp(self.request.user)
		return HttpResponseRedirect(reverse('advert:report'))		


class postUpdate(LoginRequiredMixin, UpdateView):
	model=Post
	context_object_name = 'post'
	login_url='account/login'
	partial_success_file='advert/includes/partial_post_list.html'
	partial_file='advert/includes/partial_post_update.html'

	def get(self, request, *args,**kwargs):
		dic=dict()
		self.object=self.get_object()
		form=PostForm(instance=self.object)
		data={'form':form, 'post':self.object}
		dic['html_form']=render_to_string(self.partial_file, data, request=self.request)
		return JsonResponse(dic)


	def post(self,request, *args, **kwargs):
		dic=dict()
		self.object=self.get_object()
		form=PostForm(instance=self.object, data=request.POST, files=request.FILES)
		form.save()
		data=Post.objects.filter(author=self.request.user).order_by('-published_date')
		context={'posts':data}
		dic['form_is_valid']=True
		dic['html_list']=render_to_string(self.partial_success_file,context,request=self.request)
		#return JsonResponse(dic)
		return HttpResponseRedirect(reverse('advert:post_list'))


class PostDeleteView(LoginRequiredMixin,DeleteView):
	model=Post
	login_url='account/login'
	partial_success_file='advert/includes/partial_post_list.html'
	def get(self,request, *args, **kwargs):
		data=dict()
		self.object=self.get_object()
		context = {'post': self.object }
		data['html_form'] = render_to_string('advert/includes/partial_post_delete.html',
		context,
		request=self.request,
		)
		return JsonResponse(data)

	def post(self,request, *args, **kwargs):
		dic=dict()
		data=Post.objects.filter(author=self.request.user).order_by('-published_date')
		context={'posts':data}
		self.object=self.get_object()
		self.object.delete()
		dic['form_is_valid']=True
		dic['html_list']=render_to_string(self.partial_success_file,context,request=self.request)
		return HttpResponseRedirect(reverse('advert:post_list'))


class ReportEyeView(LoginRequiredMixin,DetailView):
	model=Report
	login_url='account/login'
	partial_success_file='advert/includes/partial_report_list.html'
	def get(self,request, *args, **kwargs):
		data=dict()
		self.object=self.get_object()
		#posts=Post.objects.filter(created_date__range=[ self.object.rfrom, self.object.rto]).filter(author=self.request.user)
		posts=Post.objects.filter(Q(created_date__gte= self.object.rfrom), created_date__lte=self.object.rto).filter(author=self.request.user)
		
		count=posts.count()
		context = {'report': self.object, 'posts': posts, 'count':count, 'username':request.user.username}

		data['html_form'] = render_to_string('advert/includes/partial_report_view.html',
		context,
		request=self.request,
		)
		return JsonResponse(data)


class ReportDeleteView(LoginRequiredMixin,DeleteView):
	model=Report
	login_url='account/login'
	partial_success_file='advert/includes/partial_report_list.html'
	def get(self,request, *args, **kwargs):
		data=dict()
		self.object=self.get_object()
		context = {'report': self.object }
		data['html_form'] = render_to_string('advert/includes/partial_report_delete.html',
		context,
		request=self.request,
		)
		return JsonResponse(data)

	def post(self,request, *args, **kwargs):
		self.object=self.get_object()
		self.object.delete()
		return HttpResponseRedirect(reverse('advert:report'))


class ReportSendView(LoginRequiredMixin,DeleteView):
	model=Report
	login_url='account/login'
	partial_success_file='advert/includes/partial_report_list.html'
	def get(self,request, *args, **kwargs):
		data=dict()
		self.object=self.get_object()
		context = {'report': self.object }
		data['html_form'] = render_to_string('advert/includes/partial_report_send.html',
		context,
		request=self.request,
		)
		return JsonResponse(data)

	def post(self,request, *args, **kwargs):
		report=self.get_object()
		report.send(self.request)
		return HttpResponseRedirect(reverse('advert:report'))		

	



class PostSubmitView(LoginRequiredMixin, UpdateView):
	login_url='account/login'
	partial_success_file='advert/includes/partial_post_list.html'
	model=Post
	def get(self,request, *args, **kwargs):
		data=dict()
		self.object=self.get_object()
		context = {'post': self.object }
		data['html_form'] = render_to_string('advert/includes/partial_post_submit.html',
		context,
		request=self.request,
		)
		return JsonResponse(data)

	def post(self,request, *args, **kwargs):
		dic=dict()
		data=Post.objects.filter(author=self.request.user).order_by('-published_date')
		context={'posts':data}
		self.object=self.get_object()
		result=self.object.submit()
		if result:
			dic['form_is_valid']=True
			dic['html_list']=render_to_string(self.partial_success_file,context,request=self.request)
		else:
			dic['form_is_valid']=False
			dic['error_message']='No field can be empty. Make sure your upload a thumbnail for you post.'

		return HttpResponseRedirect(reverse('advert:post_list'))

advert/templates/advert/includes/partial_advert_update.html
<form method="post" class=".js-advert-update-form" action="{% url 'advert:update_advert' advert.id %}" enctype="multipart/form-data">
{%csrf_token %}
	<div class="modal-header text-center">
		<button type="button" class="close" data-dismiss="modal"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title">Update Advert</h4>
	</div>
	<div class="modal-body">
		{% include 'advert/includes/partial_post_form.html' %}
	<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<button class="btn modalsubmit btn-primary" type="submit">Save</button>
</form>

advert/templates/advert/includes/partial_author_list.html
        {% for author in authors %}
        <tr>
          <td><a href="{% url 'advert:author_post_list' pk=author.pk%} "><h1><strong>{{author.first_name}}</strong></h1></a></td>
          <td><h1><strong>{{author.last_name}}</strong></h1></td>
          <td><h1><strong>{{author.username}}</strong></h1></td>
          <td><h1><strong>{{author.email}}</strong></h1></td>
        </tr>
        {% endfor %}
        
      

advert/templates/advert/includes/partial_pay_form.html
<form method="post" class="js-transaction-create-form" action="{% url 'advert:create_transaction'%}">
{%csrf_token %}
	<div class="modal-header text-center">
		<button type="button" class="close" data-dismiss="modal"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title">{% if request.session.role == 'Advertiser' %}Pay into my Wallet{% else %} Withdraw {% endif %}</h4>
	</div>
	<div class="modal-body">
		{% include 'advert/includes/partial_post_form.html' %}
	<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<script src="https://js.paystack.co/v1/inline.js"></script>
	<button class="btn modalsubmit btn-primary" type="submit">Pay Now</button>
</form>

advert/templates/advert/includes/partial_post_create.html
<script>
                tinymce.init({
                 selector: 'textarea',
            relative_urls: false,
            remove_script_host: false,
            document_base_url: "https://mysite.co.za/",
            height: "360",
            image_advtab: true,
            paste_data_images: true,
            image_advtab: true,
            file_picker_callback: function(callback, value, meta) {
              if (meta.filetype == 'image') {
                $('#upload').trigger('click');
                $('#upload').on('change', function() {
                  var file = this.files[0];
                  var reader = new FileReader();
                  reader.onload = function(e) {
                    callback(e.target.result, {
                      alt: ''
                    });
                  };
                  reader.readAsDataURL(file);
                });
              }
            },
            branding:false,
            fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt",
            font_formats: "Andale Mono=andale mono,times;" +
                    "Arial=arial,helvetica,sans-serif;" +
                    "Arial Black=arial black,avant garde;" +
                    "Book Antiqua=book antiqua,palatino;" +
                    "Comic Sans MS=comic sans ms,sans-serif;" +
                    "Courier New=courier new,courier;" +
                    "Georgia=georgia,palatino;" +
                    "Helvetica=helvetica;" +
                    "Impact=impact,chicago;" +
                    "Symbol=symbol;" +
                    "Tahoma=tahoma,arial,helvetica,sans-serif;" +
                    "Terminal=terminal,monaco;" +
                    "Times New Roman=times new roman,times;" +
                    "Trebuchet MS=trebuchet ms,geneva;" +
                    "Verdana=verdana,geneva;" +
                    "Webdings=webdings;" +
                    "Wingdings=wingdings,zapf dingbats",
            plugins: "image,advlist, table, autolink, charmap, code, colorpicker, contextmenu,link, lists, paste, preview, searchreplace,  spellchecker, textcolor, wordcount,emoticons, advlist autolink lists link image charmap print preview hr anchor pagebreak",
            toolbar: "fontselect | fontsizeselect | forecolor | backcolor | bold | italic | underline | alignleft | aligncenter | alignright | alignjustify | bullist | numlist | outdent | indent | link | image | print | media | code",
            tools: "inserttable",
            contextmenu: "link image inserttable | cell row column deletetable"
                });
            </script>
<form method="post" class="js-product-create-form" action="{% url 'advert:create_post'%}" enctype="multipart/form-data">
{%csrf_token %}
	<div class="modal-header text-center">
		<button type="button" class="close" data-dismiss="modal"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title">Create New Post</h4>
	</div>
	<div class="modal-body">
		{% include 'advert/includes/partial_post_form.html' %}
	<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<button class="btn modalsubmit btn-primary" type="submit">Create</button>

</form>
<input name="image" type="file" id="upload" style="display:none" onchange="">

advert/templates/advert/includes/partial_post_feature.html
<form method="post" action="{% url 'advert:feature_post' post.id %}" class="js-post-submit-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title text-center">Confirm  Feature</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to Feature this Post <strong>{{ post.title }}</strong> on the Homepage ?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Feature Post</button>
  </div>
</form>

advert/templates/advert/includes/partial_post_list.html
        {% for post in posts %}
        <tr>
          <td><a target="_blank" href="{{post.get_absolute_url}}"><h1><strong>{{post.title}}</strong></h1></a></td>
          <td class="mobile_no">{{post.created_date|date:"SHORT_DATE_FORMAT"}}</td>
          {% if post.published_date %}
          <td class="mobile_no">{{post.published_date|date:"SHORT_DATE_FORMAT"}}</td>
          {% else %}
          <td class="mobile_no">Not yet Published</td>
          {% endif %}
          <td class="status {{post.status}}">{{post.status}}</td>
          <td> <button data-toggle="tooltip"  title="Edit Post" data-url="{% url 'advert:update_post' post.id %}"  class="js-update-product buttonicon"><span><i  class="fa fa-pencil" ></i></span></button>
          <br>
          {% if post.status == 'Draft' %}
          <button data-toggle="tooltip"  title="Delete Post" data-url="{% url 'advert:delete_post' post.id %}"  class="js-delete-product buttonicon"><span><i style="color:#f11300 ; " class="fa fa-trash"></i></span></button>
          <br>
          <button data-url="{% url 'advert:submit_post' post.id%}"  data-toggle="tooltip"  title="Save post for Review" class="js-submit-product buttonicon"><span><i style="color:green ; " class="fa fa-check"></i></span></button>
          {% else %}
            {% if request.user.is_staff and post.status != 'Published' %}
               <button data-url="{% url 'advert:publish_post' post.id%}"  data-toggle="tooltip"  title="Publish" class="js-submit-product buttonicon"><span><i style="color:green ; " class="fa fa-check"></i></span></button>
            {% endif %}
              {% if request.user.is_staff and post.status == 'Published' %}
                <button data-url="{% url 'advert:feature_post' post.id%}"  data-toggle="tooltip"  title="Feature" class="js-submit-product buttonicon"><span><i style="color:green ; " class="fa fa-check"></i></span></button>
              {% endif %}
          {% endif %}

          </td>
        </tr>
        {% endfor %}
        
      

advert/templates/advert/includes/partial_post_publish.html
<form method="post" action="{% url 'advert:publish_post' post.id %}" class="js-post-submit-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title text-center">Confirm  Publish</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to Publish this Post <strong>{{ post.title }}</strong> </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Publish Post</button>
  </div>
</form>

advert/templates/advert/includes/partial_post_submit.html
<form method="post" action="{% url 'advert:submit_post' post.id %}" class="js-post-submit-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title text-center">Confirm  Submit</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to Submit this Post <strong>{{ post.title }}</strong> for Review ?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Submit Post</button>
  </div>
</form>

advert/templates/advert/includes/partial_report_delete.html
<form method="post" action="{% url 'advert:delete_report' report.id %}" class="js-post-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title text-center">Confirm Report deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete this Report ?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Post</button>
  </div>
</form>

advert/templates/advert/includes/partial_report_list.html
  {% for report in reports %}
        <tr>
         <td class="">{{report.created_date|date:"SHORT_DATE_FORMAT"}}</td>
          <td class="">{{report.rfrom|date:"SHORT_DATE_FORMAT"}}</td>
           <td class="">{{report.rto|date:"SHORT_DATE_FORMAT"}}</td>
          <td class="">{{report.status}}</td>
          
          <td> <button data-toggle="tooltip"  title="View Report" data-url="{% url 'advert:report_posts' report.pk %}"  class="js-update-product buttonicon"><span><i  class="fa fa-eye" ></i></span></button>
          <br>
          <button data-toggle="tooltip"  title="Delete Reports" data-url="{% url 'advert:delete_report' report.pk %} "  class="js-delete-product buttonicon"><span><i style="color:#f11300 ; " class="fa fa-trash"></i></span></button>
          <br>
          {% if report.status == 'Not Sent' %}
          <button data-url="{% url 'advert:send_report' report.pk %}"  data-toggle="tooltip"  title="Send Report" class="js-submit-product buttonicon"><span><i style="color:green ; " class="fa fa-send"></i></span></button>
          {% endif %}
          </td>
        </tr>
{% endfor %}

advert/templates/advert/includes/partial_report_send.html
<form method="post" action="{% url 'advert:send_report' report.id %}" class="js-post-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title text-center">Confirm Report Send</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to Send this Report ?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Send Report</button>
  </div>
</form>

advert/templates/advert/includes/password_reset_email.html
{% autoescape off %}
Hi ,
Please click on the link to reset your password on AvetiZBlog,
Username is {{username}}

https://avetizblog.com{% url 'account:password_change_form' %}?token={{token}}&username={{username}}
{% endautoescape %}