account/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views



app_name='account'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^signup/$', views.SignUp.as_view(), name="signup"),
	url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset_form_submit'),
	url(r'^password_change_form/$', views.PasswordChangeView.as_view(), name='password_change_form'),
	#url(r'^password_change/$', views.PasswordChange.as_view(), name="password_change"),ok
    
]

advert/urls.py
from django.conf.urls import url
from . import views

app_name="advert"
urlpatterns = [
     url(r'^$', views.Dashboard.as_view(), name='dashboard'),
     url(r'^post/(?P<pk>\d+)/edit/$', views.postUpdate.as_view(), name='update_post'),
     url(r'^create_post/$', views.createPost.as_view(), name='create_post'),

     url(r'^manage_posts/$', views.postList.as_view(), name='post_list'),
     url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='delete_post'),
      url(r'^report/(?P<pk>\d+)/remove/$', views.ReportDeleteView.as_view(), name='delete_report'),
     url(r'^post/(?P<pk>\d+)/submit/$', views.PostSubmitView.as_view(), name='submit_post'),
     url(r'^post/(?P<pk>\d+)/publish/$', views.PostPublishView.as_view(), name='publish_post'),
     url(r'^post/(?P<pk>\d+)/feature_post/$', views.PostFeatureView.as_view(), name='feature_post'),
     url(r'^manage_wallet/$', views.TransactionListView.as_view(), name='transaction_list'),
     url(r'^create_transaction/$', views.TransactionCreateView.as_view(), name='create_transaction'),
     url(r'^advert_list/$', views.AdvertListView.as_view(), name='advert_list'),
     url(r'^create_advert/$', views.createAdvert.as_view(), name='create_advert'),
     url(r'^advert/(?P<pk>\d+)/remove/$', views.AdvertDeleteView.as_view(), name='delete_advert'),
     url(r'^advert/(?P<pk>\d+)/update/$', views.AdvertUpdateView.as_view(), name='update_advert'),
     url(r'^author/(?P<pk>\d+)/post_list/$', views.AuthorPostView.as_view(), name='author_post_list'),
     url(r'^profile/$', views.ProfileUpdateView.as_view(), name='profile'),
     url(r'^approve_payt/$', views.ApprovePaytView.as_view(), name='approve_payt'),
     url(r'^author_list/$', views.AuthorListView.as_view(), name='author_list'),  
     url(r'^all_post_list/$', views.AllPostView.as_view(), name='all_post_list')  ,
     url(r'^report/$', views.ReportView.as_view(), name='report') , 
     url(r'^create_report/$', views.createReport.as_view(), name='create_report'),
     url(r'^report/(?P<pk>\d+)/detail/$', views.ReportEyeView.as_view(), name='report_posts'),
      url(r'^report/(?P<pk>\d+)/send/$', views.ReportSendView.as_view(), name='send_report'),

]

blog/urls.py
from django.conf.urls import url
from . import views
from .views import FacetedSearchView, autocomplete

app_name='blog'
urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/user/(?P<pk>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^find/', FacetedSearchView.as_view(), name='haystack_search'),
    url(r'^grass-to-grace/$', views.GrassToGraceView.as_view(), name='grass_to_grace'),
    url(r'^post/(?P<slug>[-\w]+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    url(r'^create_subscriber/$', views.SubscribeView.as_view(), name='subscribe'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact_us'),
    url(r'^privacy/$', views.PrivacyView.as_view(), name='privacy_policy'),
    url(r'^terms_of_use/$', views.TermsView.as_view(), name='terms'),#test
   url(r'^activate/$', views.activate, name='activate'),
    url(r'^addview/$', views.increaseView, name='addview'),
    url(r'^newsfeed/$', views.newsfeed.as_view(), name='newsfeed'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from django.contrib import auth
from blog.views import autocomplete
app_name='blog'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^imagefit/', include('imagefit.urls')),
    url(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'', include('blog.urls')),
    url(r'^search/autocomplete/$', autocomplete),
    url(r'account/', include('account.urls')),
    url(r'^dashboard/', include('advert.urls')),
    url(r'^password_reset/$', auth.views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth.views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth.views.password_reset_complete, name='password_reset_complete'),
    #url(r'^admin/password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
   # url(r'^newsletter/', include('newsletter_signup.urls')),
]

advert/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponseRedirect
from blog.models import Post
from django.db.models import Q
from django.urls import reverse

# Create your models here.
class advertPlan(models.Model):
	name=models.CharField(max_length=50, null=True)
	cost=models.IntegerField(null=True)
	
	def __str__(self):
		return self.name


class Duration(models.Model):
	plan=models.ForeignKey(advertPlan)
	name=models.CharField(max_length=50, choices=(('1 Week', '1 Week'), ('1 Month', '1 Month'),('Quaterly', 'Quaterly'), ('Anually', 'Anually')))
	price=models.IntegerField()

	def __str__(self):
		return self.name

class Advert(models.Model):
	company=models.CharField(max_length=70)
	advert_banner=models.ImageField(upload_to='media')
	advert_desc=models.TextField()
	duration=models.CharField(max_length=50,null=True, choices=(('1 Week', '1 Week'), ('1 Month', '1 Month'),('Quaterly', 'Quaterly'), ('Anually', 'Anually')))
	status=models.BooleanField(default=False)
	publisher=models.ForeignKey(User, null=True)
	payt_status=models.BooleanField(default=False)
	created_on=models.DateField(auto_now=True)
	plan=models.ForeignKey(advertPlan, null=True)
	advert_cost=models.IntegerField(null=True)
	link=models.URLField(null=True)

	def __str__(self):
		return self.company

	def approve(self):
		self.status=True
		return True

	def setUp(self, user):
		self.advert_cost= self.duration*self.plan.cost
		self.publisher=user
		return True


class Wallet(models.Model):
	Owner=models.OneToOneField(User, on_delete=models.CASCADE)
	amount=models.IntegerField(null=True, blank=True, default="0")

class Transaction(models.Model):
	amount=models.IntegerField()
	date=models.DateTimeField(auto_now=True)
	description=models.CharField(max_length=100)
	trans_type=models.CharField(max_length=50, choices=(('Credit','Credit'),('Debit', 'Debit')))
	wallet=models.ForeignKey(Wallet)
	status=models.CharField(max_length=20, choices=(('Pending','Pending'),("Completed",'Completed')))
	ref=models.CharField(max_length=20, null=True)

	def approve(self):
		self.status='Completed'
		self.wallet.amount+=self.amount
		self.save()
		self.wallet.save()



class Report(models.Model):
	rfrom=models.DateField()
	rto=models.DateField()
	user=models.ForeignKey(User)
	status=models.CharField(max_length=90, choices=(('Sent', 'Sent'), ('Not Sent','Not Sent')), default='Not Sent')
	created_date=models.DateField(auto_now_add=True, null=True)
	description=models.TextField(null=True)

	def setUp(self, user):
		self.user=user 
		self.save()

	def send(self, request):
		posts=Post.objects.filter(Q(created_date__gte= self.rfrom), created_date__lte=self.rto).filter(author=request.user)
		
		count=posts.count()
		context = {'report': self, 'posts': posts, 'count':count, 'username':request.user.username}
		message = render_to_string('advert/includes/partial_report_view.html',context)
		
		mail_subject = 'Report from '+ request.user.username
		email = EmailMessage(mail_subject, message,'contact@avetiz.com', to=['leye@avetiz.com'], reply_to=['contact@avetiz.com'],)
		email.content_subtype = "html" 
		try:
			messages.success(request, 'Your Report has been sent . Thank You ')
			email.send()
			self.status='Sent'
		except:
			messages.warning(request, 'Your Report was not sent. Please try again ')	
		
		self.save()
		return HttpResponseRedirect(reverse('advert:report'))
		











#pk_test_d7ed8771f755bc62d8d023a93e531101a3ac4eb8

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
#from django.utils.encoding import smart_unicode




class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=400)
    text = models.TextField(blank=True)
    post_pic = models.ImageField(upload_to='media', blank=True, null=True)
    
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    featured_post = models.BooleanField(default=False)
    trending_post = models.BooleanField(default=False)
    status = models.CharField(max_length=100, default="Draft", choices=(('Draft','Draft'),('Published','Published'),('Submitted','Submitted')))
    category = models.ForeignKey('Category', null=True, blank=True)
    pageview=models.IntegerField(default=0)
    slug = models.SlugField(null=True, blank=True, max_length=200)
    

    def publish(self):
        if self.post_pic and self.text:
            self.published_date = timezone.now()
            self.status = 'Published'
            self.save()
            return True
        else:
            return False

    def submit(self):
        if self.post_pic and self.text:
            self.status='Submitted'
            self.save()
            return True
        else:
            return False

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)
       


    def approve_comments(self):
        return self.comments.filter(approved_comment=True)


    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})


    def get_cat_list(self):
        k = self.category
        breadcrumb = ["dummy"]
        while k is not None:
            breadcrumb.append(k.slug)
            k = k.parent

        for i in range(len(breadcrumb)-1):
            breadcrumb[i] = '/'.join(breadcrumb[-1:i-1:-1])
        return breadcrumb[-1:0:-1]

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    parent = models.ForeignKey('self',blank=True, null=True, related_name='children')

    class Meta:
        unique_together = ('slug', 'parent',)
        verbose_name_plural = "categories"

    def __str__(self):
        full_path = [self.name]
        k = self.parent

        while k is not None:
            full_path.append(k.name)
            k = k.parent

        return ' -> '.join(full_path[::-1])



class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self): 
        return self.text


class SubscribeEmail(models.Model):
    email=models.EmailField()
    active=models.BooleanField(default=False)
    token=models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return self.email

class ContactMessage(models.Model):
    name=models.CharField(max_length=200)
    email=models.EmailField()
    phone=models.CharField(max_length=200)
    message=models.TextField()

advert/forms.py
from django import forms

from .models import Advert, Transaction, Report
from blog.models import Post
from django.contrib.auth.models import User
from account.models import Profile
from django.contrib.auth import get_user_model
from django.contrib.admin.widgets import AdminDateWidget

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text','post_pic','category')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control borderprob' }),
            'text': forms.Textarea(attrs={'class': ' form-control'}),
            'category': forms.Select(attrs={'class':'form-control'}),
        }

class TransactionForm(forms.ModelForm):
    class Meta:
        model=Transaction
        fields=('amount', 'description')

        widgets={
            'amount':forms.NumberInput(attrs={'class':'form-control borderprob' , 'min':'0'}),
            'description': forms.TextInput(attrs={'class':'form-control borderprob'}),
        }


class advertForm(forms.ModelForm):
    class Meta:
        model=Advert
        exclude=('publisher','payt_status','advert_cost','status')

   

        widgets={
        'company':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'advert_desc':forms.Textarea(attrs={'class':'form-control'}),
        'frequency':forms.Select(attrs={'class':'form-control'}),
        'plan':forms.Select(attrs={'class':'form-control'}),
        'link':forms.TextInput(attrs={'class':'form-control borderprob'}),

        }

class reportForm(forms.ModelForm):
    class Meta:
        model=Report
        fields=('rfrom','rto','description')
        widgets={
        'rfrom':forms.DateInput(attrs={'class':'form-control'}),
        'rto':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'description':forms.Textarea(attrs={'class':'form-control borderprob'}),
        }







class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('username','first_name','last_name','email')

        widgets={
        'first_name':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'last_name':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'username':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'email':forms.EmailInput(attrs={'class':'form-control borderprob'}),
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        exclude=('user',)

        widgets={
        'phone':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'address':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'facebook_link':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'twitter_link':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'instagram_link':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'linkedin_link':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'short_description':forms.Textarea(attrs={'class':'form-control borderprob'}),
        'bank_name':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'account_name':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'account_number':forms.TextInput(attrs={'class':'form-control borderprob'}),
        }

advert/templates/advert/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'css/dash.css' %}">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
     <script src='https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=x04lrjv0qgowh7z38l1q7sqkvvgft65c39410l4gd3hvfcsy'></script>
      <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  
    <title>{% block title %}{%endblock %}</title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries-->
    <!--if lt IE 9
    script(src='https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js')
    script(src='https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js')
    -->
  </head>
  <body class="sidebar-mini fixed">
    <div class="wrapper">
      <!-- Navbar-->
      <header class="main-header hidden-print"><a class="logo" href="{% url 'blog:post_list' %}"><img style="height:50px;" class="img-responsive " src="http://test.sagecapitals.com/img/avetiz.jpg"></a>
        <nav class="navbar navbar-static-top">
          <!-- Sidebar toggle button--><a class="sidebar-toggle" href="#" data-toggle="offcanvas"></a>
          <!-- Navbar Right Menu-->
          <div class="navbar-custom-menu">
            <ul class="top-nav">
              <!--Notification Menu-->
              <!--li class="dropdown notification-menu"><a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-bell-o fa-lg"></i></a>
                <ul class="dropdown-menu">
                  <li class="not-head">You have 4 new notifications.</li>
                  <li><a class="media" href="javascript:;"><span class="media-left media-icon"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span></span>
                      <div class="media-body"><span class="block">Lisa sent you a mail</span><span class="text-muted block">2min ago</span></div></a></li>
                  <li><a class="media" href="javascript:;"><span class="media-left media-icon"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span></span>
                      <div class="media-body"><span class="block">Server Not Working</span><span class="text-muted block">2min ago</span></div></a></li>
                  <li><a class="media" href="javascript:;"><span class="media-left media-icon"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span></span>
                      <div class="media-body"><span class="block">Transaction xyz complete</span><span class="text-muted block">2min ago</span></div></a></li>
                  <li class="not-footer"><a href="#">See all notifications.</a></li>
                </ul>
              </li-->
              <!-- User Menu-->
              <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-lg"></i></a>
                <ul class="dropdown-menu settings-menu">
                  <!--li><a href="page-user.html"><i class="fa fa-cog fa-lg"></i> Settings</a></li-->
                  <li><a href="{% url 'advert:profile'%}"><i class="fa fa-user fa-lg"></i> Profile</a></li>
                  <li><a href="{% url 'account:logout' %}"><i class="fa fa-sign-out fa-lg"></i> Logout</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Side-Nav-->
      <aside class="main-sidebar hidden-print">
        <section class="sidebar">
          <div class="user-panel">
            <div class="pull-left image"><img class="img-circle" src="{{request.session.img_url}}"  alt="User Image"></div>
            <div class="pull-left info">
              <p style="text-transform:capitalize;" >{{request.user.first_name}}</p>
              <p class="designation">{{request.session.role}}</p>
            </div>
          </div>
          <!-- Sidebar Menu-->
          <ul class="sidebar-menu">
            <li class="active"><a href="{% url 'advert:dashboard' %}"><i class="fa fa-dashboard"></i><span>Dashboard</span></a></li>
            {% if request.session.role == 'Content Writer' %}
            <li><a href="{% url 'advert:post_list'%}"><i class="fa fa-file"></i><span>Manage Post</span></a></li>
            {% endif %}
             {% if request.session.role == 'Advertiser' %}
            <li><a href="{% url 'advert:advert_list' %}"><i class="fa fa-rss"></i><span>Manage Advert</span></a></li>
            {% endif %}
            {% if request.user.is_staff %}
             <li><a href="{% url 'advert:author_list' %}"><i class="fa fa-users"></i><span>Authors</span></a></li>
             <li><a href="{% url 'advert:all_post_list' %}"><i class="fa fa-file"></i><span>All Post</span></a></li>

            {% endif %}
            <li><a href="{% url 'advert:transaction_list' %}"><i class="fa fa-bank"></i><span>Manage Wallet</span></a></li>
            <li><a href="{% url 'advert:report' %}"><i class="fa fa-user"></i><span>Manage Report</span></a></li>
            <li><a href="{% url 'advert:profile' %}"><i class="fa fa-user"></i><span>Manage Profile</span></a></li>
           
  
          </ul>
        </section>
      </aside>
      {% if xyzw %}
        {% block profile %}{% endblock %}
      
      {% else %}
      <div class="content-wrapper">

        <div class="page-title">
          <div>
            <h1><i class="fa fa-dashboard"></i> Dashboard</h1>
            <p>Start a beautiful journey here with us at AvetiZBlog</p>
          </div>
          <div>
            <ul class="breadcrumb">
              <li><i class="fa fa-home fa-lg"></i></li>
              <li><a href="{% url 'advert:dashboard'%}">Dashboard</a></li>
            </ul>
          </div>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissable">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong>{{message}}</strong>
        </div>
        {%endfor%}
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    {% endif %}
    </div>
    <!-- Javascripts-->
   
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins/pace.min.js'%}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{%static 'js/blog.js' %}"></script>
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
            
      
    <script>
      
      function payWithPaystack(el){
       email= $(el).attr('email');
       id=$(el).attr('id');
       amount=$(el).attr('amount');
    var handler = PaystackPop.setup({
      // This assumes you already created a constant named
      // PAYSTACK_PUBLIC_KEY with your public key from the
      // Paystack dashboard. You can as well just paste it
      // instead of creating the constant
      key: 'pk_test_d7ed8771f755bc62d8d023a93e531101a3ac4eb8',
      email: email,
      amount: amount*100,
      ref:id,
      metadata: {
        cartid:id,
        orderid:id,
        custom_fields: [
          {
            display_name: "Paid on",
            variable_name: "paid_on",
            value: 'AvetiZBlog'
          },
          {
            display_name: "Paid via",
            variable_name: "paid_via",
            value: 'Inline Popup'
          }
        ]
      },
      callback: function(response){
        // post to server to verify transaction before giving value
        var verifying = $.get( "{% url  'advert:approve_payt' %}", {reference:response.reference} );
        verifying.done(function( data ) { /* give value saved in data */ });
      },
      onClose: function(){
        alert('Click "Pay now" to retry payment.');
      }
    });
    handler.openIframe();
    return false;
  }
    </script>
  </body>
</html>

advert/templates/advert/wallet.html
{% extends 'advert/base.html' %}
{% block content %}
<div class="row">
	<div class="col-md-4">
	    <div class="widget-small info"><i class="icon fa fa-thumbs-o-up fa-3x"></i>
	      <div class="info">
	        <h4>Total Transaction</h4>
	        <p><b>{{wallet.transaction_set.all.count}}</b></p>
	      </div>
	    </div>
	</div>
	<div class="col-md-4">
	    <div class="widget-small warning"><i class="icon fa fa-thumbs-o-up fa-3x"></i>
	      <div class="info">
	        <h4>Pending Transaction</h4>
	        <p><b>{{pt_count}}</b></p>
	      </div>
	    </div>
	</div>
	<div class="col-md-4">
	    <div class="widget-small info"><i class="icon fa fa-thumbs-o-up fa-3x"></i>
	      <div class="info">
	        <h4>Balance</h4>
	        <p><b>₦ {{wallet.amount}}</b></p>
	      </div>
	    </div>
	</div>	
</div>
<main id="maincontent">
  <section class="manage">
    <div class="container">
      <div class="row">
      	<div class="col-md-10 js-post-list ">
      	<div class="panel-body">
		  <div class="job_title">Manage Your Wallet</div>
		  <button class="createbtn btn btn-primary  js-add-transaction  " data-url="{% url 'advert:create_transaction' %}">{% if request.session.role == 'Content Writer' %}WithDraw<i class="fa fa-minus" style="color:#017583;"></i>{%else%}Credit My Account<i class="fa fa-plus" style="color:#017583;"></i>{% endif%} </button>
		    <table class="table" id="product-table">
		      <thead >
		      	<tr>
			          <th><strong>Amount</strong></th>
			          <th><strong>Created On</strong></th>
			          <th><strong>Type/Status</strong></th>
			    </tr>
		      </thead>
		      <tbody>
          			{% include 'advert/includes/partial_wallet_list.html' %}
			   </tbody>
			</table>
			</div>
         </div>
      </div>
    </div>
 
  </section>
    <div class="modal " id="modal-product">

      <div class="modal-dialog">
        <div class="modal-content"></div>
      </div>
    </div>
</main>
{% endblock %}